### PR TITLE
Automatically validate all CSVs in continuous integration

### PR DESCRIPTION
**Pull request by lematt1991**
I've created an R script that will call your `validation.R` script for every CSV file found in the repository.  I've also added a `.travis.yml` file to run this script automatically on [Travis CI](https://travis-ci.org/) everytime someone commits to the repo.  Lastly, I've added a badge to the README file that will tell people when the validation check fails.  Assuming this PR is merged, you will need to modify the README.md file to point the badge from my branch to the main master branch.

```
[![Build Status](https://travis-ci.org/ml9951/zika.svg?branch=validate-all)](https://travis-ci.org/ml9951/zika)
```

Should be changed to

```
[![Build Status](https://travis-ci.org/cdcepi/zika.svg?branch=master)](https://travis-ci.org/cdcepi/zika)
```

Additionally, you will need to activate the repository on [Travis CI](https://travis-ci.org/).

### CODE REVIEW

**Comment by dmrodz** [comment]
Thank you, Matt! Would you please run this through your updated fork and submit a PR after the validation run? That'd be super helpful. Thanks!

**Comment by lematt1991** [comment]
Just updated.  I'm still getting some errors: [[1](https://travis-ci.org/ml9951/zika#L1518-L1558)].  Accents seem to be creating some problems.

**Comment by dmrodz** [comment]
All PRs have been updated.
Whenever you're validating through travis, please do so from your fork and the submit a PR of your updated fork. Thanks a million!

**Comment by lematt1991** [comment]
If you signup and activate this repo on [Travis CI](https://travis-ci.org), then all forks will automatically get run through the test.  You can then also update the badge in the README (as indicated in the above comment) to add some visual verification that everything is passing or when something needs to be fixed.

**Comment by dmrodz** [comment]
Thanks Matt.  At the time being, we prefer not to activate the original repo on Travis CI.  Having it run on the fork and submitted as PR would be perfect for now.

**Pull request merged**
